server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:order-service}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
  
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  kafka:
    topic: ${KAFKA_TOPIC:notification-topic}
    group: ${KAFKA_GROUP:notification-group}

  clients:
    product-service:
      name: ${PRODUCT_SERVICE_NAME:product-service}
      url: ${PRODUCT_SERVICE_URL:http://localhost:6000/api/v1/products}
    user-service:
      name: ${USER_SERVICE_NAME:user-service}
      url: ${USER_SERVICE_URL:http://localhost:6000/api/v1/users}
    payment-service:
      name: ${PAYMENT_SERVICE_NAME:payment-service}
      url: ${PAYMENT_SERVICE_URL:http://localhost:6000/api/v1/payments}