server:
  port: ${SERVER_PORT:1000}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true