spring:
    application:
        name: product-service
    data:
        mongodb:
            host: localhost
            port: 27017
            database: productdb
            username: myuser
            password: mypassword
            authentication-database: admin
            connection-timeout: 1000ms
            socket-timeout: 5000ms
